name: Dr. Cyndi Worden
favicon: null
layout_spectrum: 0.8929006466642022
typography_spectrum: 0.07850301242433488
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#fefefe'
    - '#c2c2c2'
    - '#7d8d68'
    - '#3e3e3e'
  brandStrength: 0.5188709103967994
  lightness: 0.1481688243802637
  saturation: 0.5242769429460168
  rhythmicContrast: 0.15006886492483318
purpose: []
